# WZ2100 Azure build pipeline
#
# Currently contains:
#  - macOS builds

trigger:
  branches:
    include:
    - master
    - test-azure # just for testing
    - refs/tags/*

jobs:
- template: templates/macos-build-pipeline-template.yml
  parameters:
    name: macOS_Xcode_9_4_1
    displayName: 'macOS [Xcode 9.4.1, macOS 10.13 SDK]'  # friendly name to display in the UI
    vmImage: 'macOS-10.14'
    xcodeDeveloperDir: '/Applications/Xcode_9.4.1.app'
    publishArtifact: false
- template: templates/macos-build-pipeline-template.yml
  parameters:
    name: macOS_Xcode_10_3
    displayName: 'macOS [Xcode 10.3, macOS 10.14 SDK]'  # friendly name to display in the UI
    vmImage: 'macOS-10.14'
    xcodeDeveloperDir: '/Applications/Xcode_10.3.app' # Set default Xcode to Xcode 10.3 on macOS 10.14
    publishArtifact: true
    artifact: 'warzone2100_macOS'
    # Upload this macOS job's output to GitHub Releases
    uploadArtifactToGitHubReleases: true
    gitHubConnection: 'githubReleases' # Specify GitHub connection configured in Azure services connections
    #
- template: templates/macos-build-pipeline-template.yml
  parameters:
    name: macOS_Xcode_11
    displayName: 'macOS [Xcode 11.3.1, macOS 10.15 SDK]'  # friendly name to display in the UI
    vmImage: 'macOS-10.15'
    xcodeDeveloperDir: '/Applications/Xcode_11.3.1.app'
    publishArtifact: false
- template: templates/macos-build-pipeline-template.yml
  parameters:
    name: macOS_latest
    displayName: 'macOS [vmImage: macOS-latest]'  # friendly name to display in the UI
    vmImage: 'macOS-latest'
    publishArtifact: true
    artifact: 'warzone2100_macOS (latest)'
