name: Fedora

on: [push, pull_request]

jobs:
  fedora-latest-gcc:
    name: :LATEST (CMake) [GCC]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Init Git Submodules
      run: git submodule update --init --recursive
    - name: Build the Docker image
      run: |
        cd docker/fedora-latest/
        docker build -t fedora .
        cd ../..
    - name: CMake Configure
      run: docker run --rm -e "CI=true" -e GITHUB_WORKFLOW -e GITHUB_ACTION -e GITHUB_REPOSITORY -e "GITHUB_WORKSPACE=/code" -e GITHUB_SHA -e GITHUB_REF -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e MAKEFLAGS -v $(pwd):/code fedora cmake '-H.' -Bbuild -DCMAKE_BUILD_TYPE=RelWithDebInfo -DWZ_ENABLE_WARNINGS:BOOL=ON -G"Ninja"
    - name: CMake Build
      run: docker run --rm -e "CI=true" -e GITHUB_WORKFLOW -e GITHUB_ACTION -e GITHUB_REPOSITORY -e "GITHUB_WORKSPACE=/code" -e GITHUB_SHA -e GITHUB_REF -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e MAKEFLAGS -v $(pwd):/code fedora cmake --build build

  fedora-latest-gcc-m32:
    name: :LATEST (CMake) [GCC -m32]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Init Git Submodules
      run: git submodule update --init --recursive
    - name: Build the Docker image
      run: |
        cd docker/fedora-latest-m32/
        docker build -t fedora .
        cd ../..
    - name: CMake Configure
      run: docker run --rm -e "CI=true" -e GITHUB_WORKFLOW -e GITHUB_ACTION -e GITHUB_REPOSITORY -e "GITHUB_WORKSPACE=/code" -e GITHUB_SHA -e GITHUB_REF -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e MAKEFLAGS -v $(pwd):/code fedora cmake '-H.' -Bbuild -DCMAKE_TOOLCHAIN_FILE=build_tools/ci/cmake/Toolchain-Linux-cross-m32.cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DWZ_ENABLE_WARNINGS:BOOL=ON -G"Ninja"
    - name: CMake Build
      run: docker run --rm -e "CI=true" -e GITHUB_WORKFLOW -e GITHUB_ACTION -e GITHUB_REPOSITORY -e "GITHUB_WORKSPACE=/code" -e GITHUB_SHA -e GITHUB_REF -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e MAKEFLAGS -v $(pwd):/code fedora cmake --build build
