name: Test Flathub

on:
  push:
    branches-ignore:
      - 'l10n_**' # Push events to translation service branches (that begin with "l10n_")
  pull_request:
    # Match all pull requests...
    paths-ignore:
      # Except some text-only files / documentation
      - 'ChangeLog'
      # Except those that only include changes to stats
      - 'data/base/stats/**'
      - 'data/mp/stats/**'
      - 'data/mp/multiplay/script/functions/camTechEnabler.js'
      # Linux-specific example scripts
      - 'doc/hosting/linux_scripts/**'
  # Support running after "Draft Tag Release" workflow completes, as part of automated release process
  workflow_run:
    workflows: ["Draft Tag Release"]
    push:
      tags:
        - '*'
    types:
      - completed
  # Support running on Release "publish" event to build and publish to Flathub
  release:
    types:
      - published

jobs:
  test-flat-manager:
    name: 'Test Flat Manager'
    permissions:
      contents: read
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
      options: --privileged
    steps:
      - name: Install Dependencies
        run: |
          cat /etc/fedora-release

          echo "::group::dnf update"
          dnf update -y
          echo "::endgroup::"
          echo "::group::dnf install dependencies"
          dnf install -y cmake git git-lfs dbus-daemon flatpak flatpak-builder python3-aiohttp python3-tenacity python3-gobject ccache zstd curl appstream ostree-libs
          echo "::endgroup::"

          echo "::group::flatpak remote-add"
          flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak remote-add --if-not-exists flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
          flatpak remote-add --if-not-exists gnome-nightly https://nightly.gnome.org/gnome-nightly.flatpakrepo
          echo "::endgroup::"

          FLAT_MANAGER_CLIENT_URL="https://github.com/flatpak/flat-manager/releases/download/0.5.0/flat-manager-client.amd64"
          FLAT_MANAGER_CLIENT_SHA256="9733a148ac185bc8d7fb0429a43f9ad7d934635760bb71933658642c697f87c9"

          echo "::group::fetch flat-manager-client"
          curl -Lf $FLAT_MANAGER_CLIENT_URL --output /usr/bin/flat-manager-client
          echo "$FLAT_MANAGER_CLIENT_SHA256  /usr/bin/flat-manager-client" | sha256sum -c - || { echo "Error: Hash mismatch for flat-manager-client"; exit 1; }
          chmod +x /usr/bin/flat-manager-client
          echo "::endgroup::"
      - name: Test Command
        run: |
          echo "Run help"
          flat-manager-client --help
          echo "Run command that will break"
          flat-manager-client --token "invalid" create "url" "no_repo" --build-log-url "invalidurl"
