name: Ubuntu

on: [push, pull_request]

jobs:
  ubuntu-16-04-gcc:
    name: Ubuntu 16.04 (CMake) [GCC]
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: Init Git Submodules
      run: git submodule update --init --recursive
    - name: Debug Output
      run: |
        echo "GITHUB_REF=${GITHUB_REF}"
        echo "GITHUB_HEAD_REF=${GITHUB_HEAD_REF}"
    - name: Build the Docker image
      run: |
        cd docker/ubuntu-16.04/
        docker build -t ubuntu .
        cd ../..
    - name: CMake Configure
      run: docker run --rm -e "CI=true" -e GITHUB_WORKFLOW -e GITHUB_ACTION -e GITHUB_REPOSITORY -e "GITHUB_WORKSPACE=/code" -e GITHUB_SHA -e GITHUB_REF -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e MAKEFLAGS -v $(pwd):/code ubuntu cmake '-H.' -Bbuild -DCMAKE_BUILD_TYPE=RelWithDebInfo -DWZ_ENABLE_WARNINGS:BOOL=ON -G"Ninja"
    - name: CMake Build
      run: docker run --rm -e "CI=true" -e GITHUB_WORKFLOW -e GITHUB_ACTION -e GITHUB_REPOSITORY -e "GITHUB_WORKSPACE=/code" -e GITHUB_SHA -e GITHUB_REF -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e MAKEFLAGS -v $(pwd):/code ubuntu cmake --build build

  ubuntu-18-04-gcc:
    name: Ubuntu 18.04 (CMake) [GCC]
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Init Git Submodules
      run: git submodule update --init --recursive
    - name: Build the Docker image
      run: |
        cd docker/ubuntu-18.04/
        docker build -t ubuntu .
        cd ../..
    - name: CMake Configure
      run: docker run --rm -e "CI=true" -e GITHUB_WORKFLOW -e GITHUB_ACTION -e GITHUB_REPOSITORY -e "GITHUB_WORKSPACE=/code" -e GITHUB_SHA -e GITHUB_REF -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e MAKEFLAGS -v $(pwd):/code ubuntu cmake '-H.' -Bbuild -DCMAKE_BUILD_TYPE=RelWithDebInfo -DWZ_ENABLE_WARNINGS:BOOL=ON -G"Ninja"
    - name: CMake Build
      run: docker run --rm -e "CI=true" -e GITHUB_WORKFLOW -e GITHUB_ACTION -e GITHUB_REPOSITORY -e "GITHUB_WORKSPACE=/code" -e GITHUB_SHA -e GITHUB_REF -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e MAKEFLAGS -v $(pwd):/code ubuntu cmake --build build

  ubuntu-18-04-clang:
    name: Ubuntu 18.04 (CMake) [Clang]
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Init Git Submodules
      run: git submodule update --init --recursive
    - name: Build the Docker image
      run: |
        cd docker/ubuntu-18.04-clang/
        docker build -t ubuntu .
        cd ../..
    - name: CMake Configure
      run: docker run --rm -e "CI=true" -e GITHUB_WORKFLOW -e GITHUB_ACTION -e GITHUB_REPOSITORY -e "GITHUB_WORKSPACE=/code" -e GITHUB_SHA -e GITHUB_REF -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e MAKEFLAGS -v $(pwd):/code ubuntu cmake '-H.' -Bbuild -DCMAKE_BUILD_TYPE=RelWithDebInfo -DWZ_ENABLE_WARNINGS:BOOL=ON -G"Ninja"
    - name: CMake Build
      run: docker run --rm -e "CI=true" -e GITHUB_WORKFLOW -e GITHUB_ACTION -e GITHUB_REPOSITORY -e "GITHUB_WORKSPACE=/code" -e GITHUB_SHA -e GITHUB_REF -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e MAKEFLAGS -v $(pwd):/code ubuntu cmake --build build
